### ISSUE TITLE
bug: Docs and vendored regexes don't work on windows

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/linguist#1]
Regexes in [documentation.yml](https://github.com/ianlewis/linguist/blob/4e84ef081328664e8e35d17c67a2c3ef9bbac687/data/documentation.yml) and  [vendor.yml](https://github.com/ianlewis/linguist/blob/4e84ef081328664e8e35d17c67a2c3ef9bbac687/data/vendor.yml) include *nix path separators which won't match windows paths.

**Comment by dayvonjersen** [comment]
Hm, I'm not sure if this project ever worked on Windows

![linguist](https://github.com/ianlewis/linguist/assets/8731605/8cf05f14-4918-4e1c-82c7-ffdad25f9b08)

Guess it does lol. Let's update those regexes...

EDIT(day): Hm I'm actually having trouble testing this, added this to generate.go
```
//go:generate sed -i s/\//\/|\\\\/g data/documentation.yml
//go:generate sed -i s/\//\/|\\\\/g data/vendor.yml
```
which turns e.g.
```
- (^|/)README(\.|$)
```
into
```
- (^|/|\\)README(\.|$)
```

but then
```
2023/08/28 04:10:12 README.md : filename should be ignored, skipping
2023/08/28 04:10:12 with file:  \README.md
2023/08/28 04:10:12 \README.md is 5 bytes
2023/08/28 04:10:12 reading contents of \README.md
2023/08/28 04:10:12 \README.md got language hints: []string{"Markdown", "GCC Machine Description"}
2023/08/28 04:10:12 \README.md got result by data:  Markdown
```

and it's getting me wondering: is there ever a scenario where path separator is part of the filename passed to linguist? How can I test this actually does anything cause right now it's not ._.
-day

**Comment by ianlewis** [comment]
Created https://github.com/dayvonjersen/linguist/issues/9
